version: "3"

volumes:
  pgdata:
    external: true
    name: omt-tileserver-pgdata

networks:
  db:
  tileservers:

services:
  postgres:
    image: "openmaptiles/postgis:5.3"
    env_file: omt.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db

  postserve:
    image: "openmaptiles/openmaptiles-tools:5.3"
    command: >
      /bin/bash -c "pgwait && postserve /openmaptiles.yaml --verbose --serve=http://postserve:8080 --port 8080"
    env_file: omt.env
    volumes:
      - ./openmaptiles:/tileset
    networks:
      - db
      - tileservers
  
  osm-update:
    image: "openmaptiles/openmaptiles-tools:5.3"
    command: >
      /bin/bash -c "export IMPOSM_CONFIG_FILE=$$(find ./data -name *repl.json | head -1)  
      && pgwait 
      && import-update"
    env_file: omt.env
    volumes:
      - ./openmaptiles:/tileset
      - ./openmaptiles/data:/import
      - ./openmaptiles/data:/export
      - ./openmaptiles/build/sql:/sql
      - ./openmaptiles/build:/mapping
      - ./openmaptiles/cache:/cache
    networks:
      - db

  tileserver:
    image: envisionz/tileserver
    environment:
      POSTSERVE_HOST: http://postserve:8080
      TILE_FORMAT: png
    networks:
      - tileservers

  cache:
    image: envisionz/varnish
    environment:
      VARNISH_SIZE: 1G
    ports:
      - "127.0.0.1:8181:80"
    networks:
      - tileservers
