version: "3"

volumes:
  pgdata:
  data-status:
  osm-status:
  omt-import:
  omt-cache:
  omt-expired-tiles:

networks:
  db:
  tileservers:

services:
  postgres:
    image: openmaptiles/postgis:6.1
    env_file: .env-pg
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db
  
  import-data:
    image: openmaptiles/import-data:6.1
    command: >
      /bin/sh -c "([ -f /status/data-import ] || ./import_data.sh) && touch /status/data-import"
    env_file: .env
    restart: on-failure
    volumes: 
      - data-status:/status
    networks:
      - db
  
  osm-update:
    image: ghcr.io/envisionz/omt-tools:main
    command: "envnz-dl-import-update"
    env_file: .env
    volumes:
      - data-status:/status_data:ro
      - osm-status:/status_osm
      - omt-cache:/cache
      - omt-import:/import
      - omt-expired-tiles:/expired_tiles
    networks:
      - db

  postserve:
    image: ghcr.io/envisionz/omt-tools:main
    command: >
      /bin/bash -c "pgwait 
      && until [ -f /status/osm-import ]; do sleep 2; done
      && postserve openmaptiles.yaml --verbose --serve=http://postserve:8080 --port 8080"
    env_file: .env
    volumes:
      - osm-status:/status
    networks:
      - db
      - tileservers
  
  tileserver:
    image: ghcr.io/envisionz/ts-gl:main
    env_file: .env
    volumes:
      - osm-status:/status
    networks:
      - tileservers
    restart: on-failure
  
  purge-cache:
    image: ghcr.io/envisionz/omt-tools:main
    command: purge-cache
    env_file: .env
    volumes:
      - omt-expired-tiles:/expired_tiles
    networks:
      - tileservers

  cache:
    image: ghcr.io/envisionz/varnish:main
    env_file: .env
    ports:
      - "127.0.0.1:8181:8080"
    networks:
      - tileservers
