version: "3"

volumes:
  pgdata:
  status:
  omt-import:
  omt-cache:

networks:
  db:
  tileservers:

services:
  postgres:
    image: "openmaptiles/postgis:5.3"
    env_file: pg.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db
  
  import-data:
    image: "openmaptiles/import-data:5.3"
    command: >
      /bin/sh -c "([ -f /status/data-import ] || ./import_data.sh) && touch /status/data-import"
    env_file: omt.env
    restart: on-failure
    volumes: 
      - status:/status
    networks:
      - db
  
  osm-update:
    image: "envisionz/omt-tools"
    command: "envnz-dl-import-update"
    env_file: omt.env
    volumes:
      - status:/status
      - omt-cache:/cache
      - omt-import:/import
    networks:
      - db

  postserve:
    image: "envisionz/omt-tools"
    command: >
      /bin/bash -c "pgwait 
      && until [ -f /status/osm-import ]; do sleep 2; done
      && postserve openmaptiles.yaml --verbose --serve=http://postserve:8080 --port 8080"
    env_file: omt.env
    volumes:
      - status:/status
    networks:
      - db
      - tileservers
  
  tileserver:
    image: envisionz/tileserver
    environment:
      POSTSERVE_HOST: http://postserve:8080
      TILE_FORMAT: png
    networks:
      - tileservers
    restart: on-failure

  cache:
    image: envisionz/varnish
    environment:
      VARNISH_SIZE: 1G
    ports:
      - "127.0.0.1:8181:80"
    networks:
      - tileservers
