#!/bin/bash

printl()
{
    printf "%s\n" "$1"
}

export PYTHONUNBUFFERED=1

varnish_hostname=${OMT_CACHE_HOST:-cache}
min_purge=${OMT_CACHE_ZOOM_MIN:-12}
max_purge=${OMT_CACHE_ZOOM_MAX:-18}

pending=$(find /expired_tiles -name *.tiles)

until [ -z "${pending// }" ]; do
    printl "Found pending tile lists to expire: '${pending}'"
    find /expired_tiles -name *.tiles \
        -exec purge_cache.py -z "$min_purge" -Z "$max_purge" -v "$varnish_hostname" {} +
    rm -f $pending
    pending=$(find /expired_tiles -name *.tiles)
done

inotifywait -mr -e moved_to --format '%w%f' /expired_tiles/ | while read tile_file
do
    printl "Expired tile list '${tile_file}' detected"
    purge_cache.py -z "$min_purge" -Z "$max_purge" -v "$varnish_hostname" "$tile_file"
    rm -f "$tile_file"
done
