name: Create Development Docker Images

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_OMT_TOOLS: "${{ github.repository_owner }}/omt-tools"
  IMAGE_NAME_TSGL: "${{ github.repository_owner }}/ts-gl"
  IMAGE_NAME_VARNISH: "${{ github.repository_owner }}/varnish"

jobs:
  build-omt-tools:
    if: github.event_name != 'pull_request' || contains('shermp', github.actor) == false
    name: Build omt-tools ${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: ["main"]
    
    steps:         
      - uses: actions/checkout@v2
        with:
          ref: "${{matrix.branch}}"
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./omt-tools
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_OMT_TOOLS }}:${{ matrix.branch }}

  build-ts-gl:
    if: github.event_name != 'pull_request' || contains('shermp', github.actor) == false
    name: Build ts-gl ${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: ["main"]
    
    steps:         
      - uses: actions/checkout@v2
        with:
          ref: "${{matrix.branch}}"
          submodules: recursive
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ts-gl
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_TSGL }}:${{ matrix.branch }}
  
  build-varnish:
    if: github.event_name != 'pull_request' || contains('shermp', github.actor) == false
    name: Build Varnish ${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: ["main"]
    
    steps:         
      - uses: actions/checkout@v2
        with:
          ref: "${{matrix.branch}}"
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./varnish
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_VARNISH }}:${{ matrix.branch }}
